# Generated by Django 4.2.3 on 2023-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
