# Generated by Django 4.2.3 on 2024-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Librarian', 'Librarian'), ('Admin', 'Admin')], max_length=10, verbose_name='User Type'),
        ),
    ]
