# Generated by Django 4.2.3 on 2024-02-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('is_librarian', 'Can access librarian-specific functionality'), ('is_admin', 'Can access admin-specific functionality')]},
        ),
    ]
